# Generated by Django 3.0.3 on 2020-03-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doseright', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='status',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
